export default{
  Saucisse: {
    category: 'Chaud',
    name: 'Saucisse',
    priceAlone: 1.9,
    priceSandwich: 3,
    priceAmerican: 5,
  },
  Merguez: {
    category: 'Chaud',
    name: 'Merguez',
    priceAlone: 1.9,
    priceSandwich: 3,
    priceAmerican: 5,
  },
  Fricadelle: {
    category: 'Chaud',
    name: 'Fricadelle',
    priceAlone: 1.9,
    priceSandwich: 3,
    priceAmerican: 5,
  },
  Boulette: {
    category: 'Chaud',
    name: 'Boulette',
    priceAlone: 1.9,
    priceSandwich: 3,
    priceAmerican: 5,
  },
  Mexicanos: {
    category: 'Chaud',
    name: 'Mexicanos',
    priceAlone: 2.3,
    priceSandwich: 3.5,
    priceAmerican: 5.5,
  },
  Poulycroc: {
    category: 'Chaud',
    name: 'Poulycroc',
    priceAlone: 2.3,
    priceSandwich: 3.5,
    priceAmerican: 5.5,
  },
  CervelasChaud: {
    category: 'Chaud',
    name: 'Cercelas chaud',
    priceAlone: 2.5,
    priceSandwich: 3.7,
    priceAmerican: 5.7,
  },
  BrochetteBoeuf: {
    category: 'Chaud',
    name: 'Brochette boeuf',
    priceAlone: 2.9,
    priceSandwich: 4.2,
    priceAmerican: 6,
  },
  BrochettePoulet: {
    category: 'Chaud',
    name: 'Brochette poulet',
    priceAlone: 2.9,
    priceSandwich: 4.2,
    priceAmerican: 6,
  },
  BrochetteProvencale: {
    category: 'Chaud',
    name: 'Brochette provençale',
    priceAlone: 2.9,
    priceSandwich: 4.2,
    priceAmerican: 6,
  },
  Grizzly: {
    category: 'Chaud',
    name: 'Grizzly',
    priceAlone: 2.9,
    priceSandwich: 4.2,
    priceAmerican: 6,
  },
  Nugget: {
    category: 'Chaud',
    name: 'Nugget',
    priceAlone: 0.7,
    priceSandwich: 4,
    priceAmerican: 5.7,
  },
  Steak: {
    category: 'Chaud',
    name: 'Steak',
    priceAlone: 2.8,
    priceSandwich: 3.5,
    priceAmerican: 5.5,
  },
  SteakBoucher: {
    category: 'Chaud',
    name: 'Steak boucher',
    priceAlone: 3.5,
    priceSandwich: 4.2,
    priceAmerican: 6.2,
  },
};
